[package]
name = "scylla"
version = "0.1.0"
authors = ["; )"]
edition = "2018"

[dependencies]
tokio = {version = "0.3.0", features = ["net", "io-util", "sync"]}
tokio-test = "0.3.0"
bytes = "0.5"
futures = "0.3"